services:
  akhq:
    container_name: akhq
    image: tchiotludo/akhq:0.25.1
    restart: unless-stopped
    volumes:
    - ./akhq-config.yml:/app/application.yml
    ports:
      - "8090:8080"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "9000:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: 'main-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka1:9092,kafka2:9092,kafka3:9092,kafka4:9092,kafka5:9092'
      SPRING_CONFIG_ADDITIONAL-LOCATION: /app/application.yml
    volumes:
      - ./kafka-ui-config.yml:/app/application.yml
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5
    networks:
      - kafka-network

  kafka1:
    image: confluentinc/cp-kafka:7.2.0
    container_name: kafka1
    restart: unless-stopped
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093,OUTSIDE://0.0.0.0:9001
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,OUTSIDE://127.0.0.1:9001
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka-network

  kafka2:
    image: confluentinc/cp-kafka:7.2.0
    container_name: kafka2
    restart: unless-stopped
    ports:
      - "9002:9002"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093,OUTSIDE://0.0.0.0:9002
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,OUTSIDE://127.0.0.1:9002
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka-network

  kafka3:
    image: confluentinc/cp-kafka:7.2.0
    container_name: kafka3
    restart: unless-stopped
    ports:
      - "9003:9003"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093,OUTSIDE://0.0.0.0:9003
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,OUTSIDE://127.0.0.1:9003
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka-network

  kafka4:
    image: confluentinc/cp-kafka:7.2.0
    container_name: kafka4
    restart: unless-stopped
    ports:
      - "9004:9004"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka4:9092,CONTROLLER://kafka4:9093,OUTSIDE://0.0.0.0:9004
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka4:9092,OUTSIDE://127.0.0.1:9004
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka-network

  kafka5:
    image: confluentinc/cp-kafka:7.2.0
    container_name: kafka5
    restart: unless-stopped
    ports:
      - "9005:9005"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka5:9092,CONTROLLER://kafka5:9093,OUTSIDE://0.0.0.0:9005
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka5:9092,OUTSIDE://127.0.0.1:9005
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
