version: "3.9"

services:
  zookeeper:
    platform: linux/amd64
    container_name: zookeeper
    image: gitlab-registry.ozon.ru/route-mentors/kafka-workshops/confluentinc/cp-zookeeper:7.2.0
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-network


  kafka-ui:
    image: gitlab-registry.ozon.ru/route-mentors/kafka-workshops/provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8084:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka_1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:32181
    depends_on:
      - zookeeper
      - kafka_1
    networks:
      - kafka-network
  kafka_1:
    platform: linux/amd64
    container_name: kafka_1
    image: gitlab-registry.ozon.ru/route-mentors/kafka-workshops/confluentinc/cp-kafka:7.2.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_1:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command: sh -c "((sleep 15 && kafka-topics --create --zookeeper zookeeper:32181 --replication-factor 1 --partitions 1 --topic templates)&) && /etc/confluent/docker/run"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
