monitoring:
  expvar: { enabled: true }
pools:
  - gun:
      type: kafka_producer
      kafka_config:
        kafka_brokers:
          - localhost:9094
        kafka_version: 3.1.0
        network_config:
          max_open_requests: 500
          dial_timeout: 35s
          read_timeout: 35s
          write_timeout: 35s
          keep_alive: 0
        metadata_config:
          retry:
            max: 5
            backoff: 250ms
          refresh_frequency: 10m
          full: true
          timeout: 0
          allow_auto_topic_creation: false
        producer_config:
          max_message_bytes: 20971520
          required_acks: 1 # NoResponse = 0, WaitForLocal= 1, WaitForAll = -1
          timeout: 10s
          compression: 4
          compression_level: -3
          partitioner: hash
          idempotent: False
          flush:
            bytes: 314280
            messages: 10000 # - Оптимальное количество сообщений в пачке
            max_messages: 1000000 # - Максимальное количество сообщений в пачке при флаше в кафку
            frequency: 100ns # -При высокой интенсивности надо уменьшать частоту флаша сообщений в кафку
          retry:
            max: 5
            backoff: 100ms
    ammo:
      type: kafka/binary
      Passes: 1
      source:
        path: './kafka.ammo'
        type: file
    result:
      type: phout
      destination: ./http_phout.log
#    rps-per-instance: true
    rps:
      type: unlimited
      duration: 1m
    startup:
      type: once
      times: 1
log:
  level: debug
